lakekeeper/lakekeeper

- .gitignore
- crates/iceberg-ext/src/catalog/rest/catalog_config.rs
- crates/iceberg-ext/src/catalog/rest/namespace.rs
- crates/iceberg-ext/src/catalog/rest/table.rs
- crates/iceberg-ext/src/spec/table_metadata.rs
- crates/iceberg-rest-server/migrations/04_namespace.sql
- crates/iceberg-rest-server/migrations/05_table.sql
- crates/iceberg-rest-server/src/config.rs
- crates/iceberg-rest-server/src/implementations/postgres/namespace.rs
- justfile
Fixes https://github.com/hansetag/iceberg-rest-server/issues/30
> Make tables & namespaces case-insensitive in PG

- crates/iceberg-rest-bin/src/main.rs
- crates/iceberg-rest-server/src/api/mod.rs
- crates/iceberg-rest-server/src/api/v1/warehouse.rs
- crates/iceberg-rest-server/src/catalog/config.rs
- crates/iceberg-rest-server/src/catalog/metrics.rs
- crates/iceberg-rest-server/src/catalog/mod.rs
- crates/iceberg-rest-server/src/catalog/namespace.rs
- crates/iceberg-rest-server/src/catalog/s3_signer.rs
- crates/iceberg-rest-server/src/catalog/tables.rs
- crates/iceberg-rest-server/src/implementations/postgres/table.rs
- crates/iceberg-rest-server/src/service/event_publisher.rs
- crates/iceberg-rest-server/src/service/mod.rs
- crates/iceberg-rest-server/src/service/router.rs
> add Publisher trait + dummy impls

- .cargo/audit.toml
- Cargo.toml
- crates/iceberg-rest-bin/Cargo.toml
- crates/iceberg-rest-bin/src/main.rs
- crates/iceberg-rest-server/Cargo.toml
- crates/iceberg-rest-server/src/config.rs
- crates/iceberg-rest-service/Cargo.toml
move to clap to get rid of yaml-rust & add audit.toml to ignore the false positive in mysql
Closes #4
> Fix security advisories & move to clap

- crates/iceberg-catalog/src/catalog/tables.rs
Don't publish the full request for each table change on commit-transaction.
> Fix commit transaction event body

- Cargo.toml
- crates/iceberg-catalog/src/catalog/tables.rs
Upstream merged: https://github.com/apache/iceberg-rust/pull/402
> Use TableUpdate.clone() from upstream

- .github/workflows/ci.yml
- tests/docker-compose.yaml
service_started is not enough for nats, this adds a health check, seems to fix flaky CI
> Fix flaky tests

- docker/bin.Dockerfile
- docker/full.Dockerfile
- examples/notebooks/Multiple Warehouses.ipynb
- tests/docker-compose.yaml
This avoids some of the unrelated CVE messages we are getting on quay.io
> chore: use distroless images

- .github/workflows/test-examples.yml
- examples/docker-compose.yaml
- tests/docker-compose.yaml
> fix(examples): add pipeline check for examples & fix examples

- crates/iceberg-catalog/src/catalog/tables.rs
- crates/iceberg-catalog/src/catalog/views.rs
- crates/iceberg-catalog/src/implementations/authz.rs
- crates/iceberg-catalog/src/implementations/postgres/catalog.rs
- crates/iceberg-catalog/src/implementations/postgres/tabular.rs
- crates/iceberg-catalog/src/implementations/postgres/tabular/view.rs
- crates/iceberg-catalog/src/service/auth.rs
- crates/iceberg-catalog/src/service/catalog.rs
- add authz interfaces for views
- add calls to respective authz interface to service layer
- add view-ident -> view-uuid resolve fn to enable authz functionality
> feat(views): authz interface for views & view-ident resolve

- crates/iceberg-catalog/src/implementations/postgres/dbutils.rs
> fix(db): transaction failure should not give internal error

- README.md
- crates/iceberg-catalog-bin/src/main.rs
- crates/iceberg-catalog/src/config.rs
> feat(server): make listenport configurable

- Cargo.lock
- crates/iceberg-catalog-bin/Cargo.toml
- crates/iceberg-catalog-bin/src/main.rs
- justfile
- openapi/management-open-api.yaml
> feat(openapi): management openapi spec

- DEVELOPER_GUIDE.md
- examples/docker-compose-latest.yaml
Makes testing things locally a bit easier
> feat(dev): docker compose from sources

- crates/iceberg-catalog/src/catalog/tables.rs
> fix(tables): deny unsupported table metadata properties

- Cargo.lock
- Cargo.toml
- crates/iceberg-catalog-bin/Cargo.toml
- crates/iceberg-catalog/Cargo.toml
- docker/bin.Dockerfile
- docker/full.Dockerfile
- tests/docker-compose.yaml
1. Remove unused deps
2. Move from plain cc distroless to a subset image that only keeps deps that we need, should remove some CVE noise
> chore(deps): dependency maintenance

- Cargo.lock
- Cargo.toml
- crates/iceberg-catalog/Cargo.toml
- crates/iceberg-catalog/src/api/management/mod.rs
- crates/iceberg-catalog/src/api/management/v1/warehouse.rs
- crates/iceberg-catalog/src/catalog/io.rs
- crates/iceberg-catalog/src/catalog/s3_signer.rs
- crates/iceberg-catalog/src/catalog/tables.rs
- crates/iceberg-catalog/src/catalog/views/commit.rs
- crates/iceberg-catalog/src/catalog/views/create.rs
- crates/iceberg-catalog/src/catalog/views/load.rs
- crates/iceberg-catalog/src/implementations/postgres/tabular/table.rs
- crates/iceberg-catalog/src/service/storage/az.rs
- crates/iceberg-catalog/src/service/storage/error.rs
- crates/iceberg-catalog/src/service/storage/mod.rs
- crates/iceberg-catalog/src/service/storage/s3.rs
- openapi/management-open-api.yaml
azure datalake storage support, currently relies on forks of iceberg-rust -> opendal -> reqsign
we're also pulling in a lot of azure sdk dependencies just for the sas token stuff + validating the storage profile, once FileIO is up to speed we may wanna reconsider this, reqsign also has some sas facilities.
> feat(storage): azdls

- crates/iceberg-catalog/src/catalog/namespace.rs
> fix!: dots can no longer be used in namespace names

- .github/workflows/test-examples.yml
- examples/create-default-warehouse.json
- examples/docker-compose.yaml
- missing keys in json
- add check to ci which ensures warehouse creation succeeds
> fix(examples): fix examples

- Cargo.lock
- Cargo.toml
- crates/iceberg-ext/src/spec/partition_binder.rs
- crates/iceberg-ext/src/spec/table_metadata.rs
- opendal -> 49.1
- iceberg-rust -> rebase on latest main
> chore(deps): Update forks

- .github/workflows/unittests.yml
> run az & s3 tests in ci

- README.md
- STORAGE.md
- USER_GUIDE.md
- examples/notebooks/Multiple Warehouses.ipynb
- examples/notebooks/Spark Configuration.ipynb
- Correction for NATS environment variable name
- Document ipynb a bit more, so that it can be used as starting point outside of provided docker testing environment
- Make a few things more explicit/clear in STORAGE.md and USER+GUIDE.md
> docs: Suggestions and small correction for docs

- crates/iceberg-catalog/src/catalog/namespace.rs
- crates/iceberg-catalog/src/catalog/tables.rs
> fix: replace pretty debug prints with properly formatted errors

- Cargo.lock
- Cargo.toml
- crates/iceberg-catalog/Cargo.toml
> chore(deps): use upstream needs-env-var

- crates/iceberg-catalog-bin/src/serve.rs
- crates/iceberg-catalog/src/catalog/namespace.rs
- crates/iceberg-catalog/src/service/authz/implementations/mod.rs
- crates/iceberg-catalog/src/service/authz/implementations/openfga/api.rs
- crates/iceberg-catalog/src/service/authz/implementations/openfga/client.rs
- crates/iceberg-catalog/src/service/authz/implementations/openfga/error.rs
- crates/iceberg-catalog/src/service/authz/implementations/openfga/health.rs
- crates/iceberg-catalog/src/service/authz/implementations/openfga/migration.rs
- crates/iceberg-catalog/src/service/authz/implementations/openfga/mod.rs
- crates/iceberg-catalog/src/service/authz/implementations/openfga/service_ext.rs
fewer generics being lugged around
> use tower layer instead of intercepted channel

- Cargo.lock
- Cargo.toml
- crates/iceberg-catalog/src/service/storage/az.rs
reuses http clients against azure and reduces fetching sas from 800ms to 200ms for subsequent calls, also makes creation of table faster, down from 1700ms to 1200ms
#359
> feat: improve azure latency by reusing http clients

- crates/iceberg-catalog/CHANGELOG.md
- crates/iceberg-catalog/src/api/management/mod.rs
- crates/iceberg-catalog/src/api/management/v1/project.rs
- crates/iceberg-catalog/src/api/management/v1/warehouse.rs
- crates/iceberg-catalog/src/service/storage/az.rs
- crates/iceberg-catalog/src/service/storage/mod.rs
- openapi/management-open-api.yaml
- tests/python/tests/conftest.py
- tests/python/tests/test_spark.py
Fixes https://github.com/lakekeeper/lakekeeper/issues/337
> chore: Rename AZDLS -> ADLS

- crates/iceberg-catalog/src/catalog/s3_signer/sign.rs
this fixes aws s3 with spark which doesn't request vended credentials
> fix: aws s3 signer

- crates/iceberg-catalog/src/service/storage/s3.rs
> feat: improve latency against aws by reusing http clients

- .github/workflows/unittests.yml
- Cargo.lock
- openapi/management-open-api.yaml
Release please changes those and it upsets the action
> chore: git diff unit-test ignore lines containing version

- tests/python/tests/conftest.py
This will hopefully make our spark tests use vended / remote signing
> fix(tests): configure spark for vended / remote signing

- USER_GUIDE.md
> chore(docs-spelling) spelling typo in example

- README.md
Just adding a small fix to ensure the commands work and some minor clarifications
> Update README.md for Quickstart

- .github/workflows/site.yml
- site/dev/common.sh
- site/dev/deploy.sh
- site/justfile
- site/mkdocs.yml
Adding some initial scripts to deploy multiple docs versions to GitHub Pages.
> Add simple github pages deploy

- crates/iceberg-catalog/src/api/management/v1/project.rs
- crates/iceberg-catalog/src/api/management/v1/warehouse.rs
- crates/iceberg-catalog/src/catalog/namespace.rs
- crates/iceberg-catalog/src/catalog/tables.rs
- crates/iceberg-catalog/src/catalog/views/exists.rs
- crates/iceberg-catalog/src/catalog/views/load.rs
further addresses #623 
Same as #636 but for views, even though we were committing here, we still do it after reading secret which could hang.
> fix: potential deadlock also for views

- Cargo.lock
- crates/iceberg-catalog/src/api/management/mod.rs
- crates/iceberg-ext/Cargo.toml
- crates/iceberg-ext/src/catalog/mod.rs
- crates/iceberg-ext/src/catalog/rest/error.rs
- openapi/management-open-api.yaml
> feat(openapi): document error models in openapi

- Cargo.lock
- Cargo.toml
Fixes https://github.com/lakekeeper/lakekeeper/issues/663
> fix: TLS encryption to OpenFGA

- README.md
- docs/docs/gotchas.md
- site/docs/getting-started.md
> chore: state postgres requirement in docs

- crates/iceberg-catalog/src/catalog/commit_tables.rs
- crates/iceberg-catalog/src/catalog/mod.rs
- crates/iceberg-catalog/src/catalog/namespace.rs
- crates/iceberg-catalog/src/implementations/postgres/namespace.rs
- warehouse creation
- table updates
- namespace creation
> chore(observability): improve observability of some endpoints

- Cargo.lock
- Cargo.toml
- crates/iceberg-catalog/src/config.rs
- crates/iceberg-catalog/src/service/authz/implementations/openfga/client.rs
- docs/docs/configuration.md
- examples/access-control/docker-compose-build.yaml
- examples/access-control/docker-compose.yaml
- examples/access-control/keycloak/realm.json
- examples/trino-opa/keycloak/realm.json
Fixes: https://github.com/lakekeeper/lakekeeper/issues/851
> fix: Client Credential Authentication for OpenFGA, allow to configure Scopes

- crates/iceberg-catalog/src/service/storage/s3.rs
- docs/docs/storage.md
> fix: forward sts role arn to s3-compatible storages when specified

- crates/iceberg-catalog/src/service/storage/az.rs
Currently, we set the start time of the sas token to now(), which can be in the future from azure's point of view, which makes calls fail that use that token. By putting start 5 minutes into the past, there's some tolerance for clock drift.
> fix(az): relax sas token start time

- docs/docs/engines.md
Fixed a small typo in docs for first commit :)
> fixed typo in docs

- .github/workflows/unittests.yml
- Cargo.lock
- Cargo.toml
- crates/iceberg-catalog/src/catalog/compression_codec.rs
- crates/iceberg-catalog/src/catalog/views/commit.rs
- crates/iceberg-catalog/src/catalog/views/create.rs
- crates/iceberg-catalog/src/catalog/views/load.rs
- crates/iceberg-catalog/src/implementations/postgres/tabular/view/load.rs
- crates/iceberg-catalog/src/implementations/postgres/tabular/view/mod.rs
- crates/iceberg-catalog/src/service/contract_verification.rs
- crates/iceberg-catalog/src/service/storage/az.rs
- crates/iceberg-catalog/src/service/storage/mod.rs
- docs/docs/api/management-open-api.yaml
> feat(az): support azure shared keys

- authz/opa-bridge/policies/trino/allow_table.rego
- crates/iceberg-catalog/src/catalog/views/commit.rs
- tests/python/tests/conftest.py
- tests/python/tests/test_trino.py
> feat(view): allow view location updates for trino

- crates/iceberg-catalog/src/catalog/views/drop.rs
> fix: set 404 instead of 403 on failed view deletion

- crates/iceberg-catalog/src/api/management/v1/user.rs
- docs/docs/authentication.md
…ing app_displayname in Entra-ID token)
> feat: Accept nameless Application Clients for self-provisioning (Missing app_displayname in Entra-ID token)

- site/overrides/home.html
> chore(docs): Iceberg Meetup Europe videos

- Cargo.lock
- crates/iceberg-catalog-bin/Cargo.toml
- crates/iceberg-catalog-bin/src/serve.rs
- crates/iceberg-catalog-bin/src/ui.rs
Fixes: https://github.com/lakekeeper/lakekeeper/pull/980
> Feat: Update UI to Version 0.6.0, Fix Favicon

- .github/workflows/unittests.yml
- crates/iceberg-catalog/src/service/storage/s3.rs
- docs/docs/api/management-open-api.yaml
- docs/docs/storage.md
fixes: https://github.com/lakekeeper/lakekeeper/issues/1022
> feat: Support for AWS S3 Buckets with KMS

- tests/python/tests/test_pyiceberg.py
Updates the test suite to align with https://py.iceberg.apache.org/reference/pyiceberg/exceptions/:
- Replaces references to table-namespace errors with `NamespaceAlreadyExistsError`
for already-existing namespaces.
- Updates the single-part table identifier check to raise `NoSuchTableError`
rather than `NoSuchNamespaceError`.
Ran `docker compose run spark /opt/entrypoint.sh bash -c "cd /opt/tests && bash run.sh pyiceberg"` and ensured there's no regression:
```
tests/test_pyiceberg.py ⨯✓✓✓✓s✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓                                                                                                                        100% ██████████
=============================================================================== short test summary info …
```
> test: use PyIceberg exception classes in Lakekeeper tests

- crates/iceberg-catalog/src/service/authz/mod.rs
> fix: trino show tables needs 404 instead of 403

- crates/lakekeeper/src/implementations/postgres/tabular/table/commit.rs
Closes https://github.com/lakekeeper/lakekeeper/issues/1147
> fix: Error code for concurrent updates

- docs/docs/authorization.md
Currently the doc is pointing to the incorrect schema path `v1` that doesn't exist.
Updated it to the correct path.
> Update `authorization.md` to refer to correct `schema.fga` file

- Cargo.lock
- Cargo.toml
Closes https://github.com/lakekeeper/lakekeeper/issues/1173
> feat: enable external-account feature in gcloud-auth crate

- crates/lakekeeper/src/implementations/postgres/migrations/mod.rs
Fixes an issue that prevents updates from 0.9.0 to 0.9.1
> fix: Add changed missing changed migration

- crates/lakekeeper/src/catalog/mod.rs
- docs/docs/configuration.md
Closes https://github.com/lakekeeper/lakekeeper/issues/1215
> fix: return MAX_PAGE_SIZE entries if pageToken is not specified

- crates/lakekeeper/src/api/management/v1/warehouse/mod.rs
Closes https://github.com/lakekeeper/lakekeeper/issues/1234
> fix: Create Warehouse Endpoint should respect X-Project-ID Header

- crates/lakekeeper/src/config.rs
- crates/lakekeeper/src/service/storage/mod.rs
- docs/docs/configuration.md
Closes https://github.com/lakekeeper/lakekeeper/issues/1220
> feat: Globally disable storage validation

- crates/lakekeeper/src/implementations/postgres/pagination.rs
Hi team,
I'm a regular contributor to the iceberg-go repo and would love to start contributing to this repository as well. To begin, I'm planning to make some small improvements to the unit tests as a way to get familiar with the codebase.
Any feedback or suggestions from the team would be greatly appreciated!
> Add unittest for PaginateToken
