lakekeeper/lakekeeper

crates/iceberg-rest-server/src/catalog/namespace.rs, crates/iceberg-rest-server/src/config.rs
#12 
Reserved `system` and `examples` namespaces for internal use.
Now we can specify reserved namespaces for each deployment with env var like so:
`ICEBERG_REST__RESERVED_NAMESPACES=reserved_namespace,reserved_namespace2,reserved_namespace3`
=> Add reservation of namespaces

Cargo.toml, crates/iceberg-rest-bin/Cargo.toml, crates/iceberg-rest-bin/src/main.rs, crates/iceberg-rest-server/Cargo.toml, crates/iceberg-rest-server/src/api/mod.rs, crates/iceberg-rest-server/src/api/v1/warehouse.rs, crates/iceberg-rest-server/src/catalog/config.rs, crates/iceberg-rest-server/src/catalog/metrics.rs, crates/iceberg-rest-server/src/catalog/namespace.rs, crates/iceberg-rest-server/src/catalog/s3_signer.rs, crates/iceberg-rest-server/src/catalog/tables.rs, crates/iceberg-rest-server/src/implementations/authz.rs, crates/iceberg-rest-server/src/lib.rs, crates/iceberg-rest-server/src/request_metadata.rs, crates/iceberg-rest-server/src/service/auth.rs, crates/iceberg-rest-server/src/service/router.rs, crates/iceberg-rest-server/src/tracing.rs, crates/iceberg-rest-service/src/service.rs, crates/iceberg-rest-service/src/service/v1/config.rs, crates/iceberg-rest-service/src/service/v1/metrics.rs, crates/iceberg-rest-service/src/service/v1/namespace.rs, crates/iceberg-rest-service/src/service/v1/oauth.rs, crates/iceberg-rest-service/src/service/v1/s3_signer.rs, crates/iceberg-rest-service/src/service/v1/tables.rs, crates/iceberg-rest-service/src/service/v1/views.rs
#59 generates a request_id via tower and makes it available via RequestMetadata in all routes & their handlers
#28 moves to tracing & uses json as logformat
=> use tracing + generate request ids

Cargo.lock, crates/iceberg-catalog/src/api/iceberg/v1/config.rs, crates/iceberg-catalog/src/api/iceberg/v1/namespace.rs, crates/iceberg-catalog/src/catalog/io.rs, crates/iceberg-catalog/src/catalog/namespace.rs, crates/iceberg-catalog/src/catalog/s3_signer.rs, crates/iceberg-catalog/src/catalog/tables.rs, crates/iceberg-catalog/src/implementations/postgres/dbutils.rs, crates/iceberg-catalog/src/implementations/postgres/namespace.rs, crates/iceberg-catalog/src/implementations/postgres/secrets.rs, crates/iceberg-catalog/src/implementations/postgres/tabular.rs, crates/iceberg-catalog/src/implementations/postgres/tabular/table.rs, crates/iceberg-catalog/src/implementations/postgres/tabular/view.rs, crates/iceberg-catalog/src/implementations/postgres/tabular/view/load.rs, crates/iceberg-catalog/src/implementations/postgres/warehouse.rs, crates/iceberg-catalog/src/service/mod.rs, crates/iceberg-catalog/src/service/storage/mod.rs, crates/iceberg-catalog/src/service/storage/s3.rs, crates/iceberg-catalog/src/service/token_verification.rs, crates/iceberg-ext/Cargo.toml, crates/iceberg-ext/src/catalog/mod.rs, crates/iceberg-ext/src/catalog/rest/error.rs, crates/iceberg-ext/src/catalog/rest/table.rs, crates/iceberg-ext/src/spec/partition_binder.rs, crates/iceberg-ext/src/spec/table_metadata.rs
fewer changes, add source to error model + variant constructors, doesn't use them everywhere, also decouple internal error from api surface error to avoid any leakage
Partially addresses:
#81
=> chore: refactor errors

Cargo.lock, crates/iceberg-catalog-bin/src/main.rs, crates/iceberg-catalog/Cargo.toml, crates/iceberg-catalog/src/api/iceberg/v1/tables.rs, crates/iceberg-catalog/src/api/router.rs, crates/iceberg-catalog/src/catalog/mod.rs, crates/iceberg-catalog/src/catalog/views.rs, crates/iceberg-catalog/src/config.rs, crates/iceberg-catalog/src/implementations/authz.rs, crates/iceberg-catalog/src/implementations/postgres/catalog.rs, crates/iceberg-catalog/src/implementations/postgres/mod.rs, crates/iceberg-catalog/src/implementations/postgres/namespace.rs, crates/iceberg-catalog/src/implementations/postgres/secrets.rs, crates/iceberg-catalog/src/implementations/postgres/tabular.rs, crates/iceberg-catalog/src/implementations/postgres/tabular/table.rs, crates/iceberg-catalog/src/implementations/postgres/tabular/view.rs, crates/iceberg-catalog/src/implementations/postgres/warehouse.rs, crates/iceberg-catalog/src/lib.rs, crates/iceberg-catalog/src/service/catalog.rs, crates/iceberg-catalog/src/service/health.rs, crates/iceberg-catalog/src/service/mod.rs, crates/iceberg-catalog/src/service/secrets.rs
closes #35 
`curl server:8080/health`
```json
{
"health": "ok",
"services": {
"secrets": [
{
"name": "read_pool",
"lastCheck": 1721314813908,
"status": "ok"
},
{
"name": "write_pool",
"lastCheck": 1721314813908,
"status": "ok"
}
],
"auth": [],
"catalog": [
{
"name": "read_pool",
"lastCheck": 1721314813940,
"status": "ok"
},
{
"name": "write_pool",
"lastCheck": 1721314813940,
"status": "ok"
}
]
}
}
```
closes #168 
1. only check db `healthcheck -d`, requires postgres connection envs to be set
2. only check server `healtcheck -s` calls `/health` on `localhost:8080` as previously but inspects the response
3. check db & server `healthcheck -a` combines `-d` and `-s`
4. check if db migrations match binary: `ensure-migrate`, requires postgres connection envs to be set
=> Service health checks

Cargo.lock, Cargo.toml, README.md, crates/iceberg-catalog-bin/src/main.rs, crates/iceberg-catalog/Cargo.toml, crates/iceberg-catalog/src/api/router.rs, crates/iceberg-catalog/src/config.rs, crates/iceberg-catalog/src/lib.rs, crates/iceberg-catalog/src/metrics.rs
- serves metrics under `0.0.0.0:<ICEBERG_REST__METRICS_PORT>`
- does not serve metrics for calls to metrics
- serves metrics for calls to health
- we may wanna consider moving /health under `ICEBERG_REST__METRICS_PORT` as well
closes #87
=> feat(prometheus): add prometheus axum metrics

crates/iceberg-catalog/src/catalog/s3_signer.rs, examples/docker-compose.yaml
BEGIN_COMMIT_OVERRIDE
fix(s3signing): Add S3 remote signing "content-md5" for pyiceberg compatability
fix(examples): Fix `ICEBERG_REST__BASE_URI`
END_COMMIT_OVERRIDE
=> fix: Add S3 remote signing "content-md5" for pyiceberg compatability

STORAGE.md
Only way I got it working with my local setup. Otherwise I get an error 
```[text]
Failed to deserialize the JSON body into the target type: storage-profile: missing field `sts-enabled` at line 14 column 5
```
=> fix(doc) Add sts-enabled for minio storage-profile

.github/workflows/unittests.yml, DEVELOPER_GUIDE.md, crates/iceberg-catalog/src/implementations/kv2.rs
removes one external dependency from running unittests, we still run the tests on ci so we keep the guarantees
closes #259
=> chore(kv2): make tests env-var dependent

.cargo/audit.toml
Currently, there's no available fix, we should bump sqlx to 0.8.1 as soon as it's here. Until then, CI is either blocked or we ignore the advisory.
https://github.com/hansetag/iceberg-catalog/issues/280
=> ignore RUSTSEC-2024-0363

Cargo.lock, crates/iceberg-catalog/Cargo.toml, crates/iceberg-catalog/src/implementations/kv2.rs, crates/iceberg-catalog/src/service/storage/az.rs, crates/iceberg-catalog/src/service/storage/s3.rs
currently, we have failures in CI for non-maintainer PRs (https://github.com/hansetag/iceberg-catalog/pull/309), this is due to `needs_env_var` checking for absence / presence of an env while github actions ends up mounting an empty secret for non-maintainer PRs. This PR moves us from crates.io `needs_env_var` to a fork.
There's a PR at `needs_env_var` to upstream the matching logic: https://github.com/HerrMuellerluedenscheid/needs_env_var/pull/2
=> fix: make conditional compilation of tests depend on var content

Cargo.lock, Cargo.toml, README.md
This should fix self-signed certs. Tested locally with minio with a certificate generated via [certgen](https://github.com/minio/certgen) `./certgen-darwin-arm64 -host "127.0.0.1,localhost,minio" --no-ca`, discovered the following quirks:
- the cert cannot be a CA (client will fail with `CaUsedAsEndEntity`, see https://github.com/lightningnetwork/lnd/issues/5450#issuecomment-2419544062):
> The error CaUsedAsEndEntity indicates that Rustls is rejecting the server’s certificate because it is a CA certificate being used as an end-entity certificate, which is not allowed by default in TLS protocols. Rustls adheres strictly to the TLS specification and security best practices, so it flags this usage as invalid.
In TLS, the server certificate presented during the handshake should be an …
=> feat: enable native-tls-root-certs

tests/docker-compose.yaml
There was a wrong key in `tests/docker-compose.yaml`
=> fix: nats in tests

crates/iceberg-catalog/src/catalog/tables.rs, crates/iceberg-catalog/src/catalog/views/commit.rs, crates/iceberg-catalog/src/catalog/views/create.rs, crates/iceberg-catalog/src/service/storage/mod.rs
we're going for the string parsing route here, we could also store the version number in the db, wdyt @c-thiel?
Python is parsing strings:
```py
@staticmethod
def _parse_metadata_version(metadata_location: str) -> int:
"""Parse the version from the metadata location.
The version is the first part of the file name, before the first dash.
For example, the version of the metadata file
`s3://bucket/db/tb/metadata/00001-6c97e413-d51b-4538-ac70-12fe2a85cb83.metadata.json`
is 1.
If the path does not comply with the pattern, the version is defaulted to be -1, ensuring
that the next metadata file is treated as having version 0.
Args:
metadata_location (str): The location of the metadata file.
Returns:
int: The version of the metadata file. -1 if the file name does not have valid version string
""" …
```
=> fix: prepend a version count to metadata files

.github/workflows/unittests.yml, Cargo.lock, openapi/management-open-api.yaml
release please PR currently fails due to incremented version number being detected as diff
this changes the diff to just care about openapi & cargo.lock, Cargo.lock was added since it broke main build from time to time
=> fix: release please

.cargo/audit.toml
1. We depend on proc-macro-error through utoipa < 0.5, upgrading to utoipa 0.5 is blocked by #563, since it's just an unmaintained dependency without direct security implications, we should ignore the advisory for now to unblock other PRs here and target upgrading utoipa to 0.5 in the near future.
2. [RUSTSEC-2024-0399](https://rustsec.org/advisories/RUSTSEC-2024-0399) shouldn't apply to us since we are not terminating tls but are just using rustls in various clients
3.  [RUSTSEC-2024-0384](https://rustsec.org/advisories/RUSTSEC-2024-0384) considered unmaintained but no known harm, we should update azure through which we depend once they upgrade their dependencies
=> chore: ignore proc-macro-error & rustls advisories

.github/workflows/integration_test_workflow.yml, Cargo.lock, Cargo.toml, crates/iceberg-catalog/Cargo.toml, crates/iceberg-catalog/src/catalog/io.rs, crates/iceberg-catalog/src/catalog/tables.rs, crates/iceberg-catalog/src/lib.rs, crates/iceberg-catalog/src/retry.rs, crates/iceberg-catalog/src/service/storage/mod.rs, crates/iceberg-catalog/src/service/storage/s3.rs
Wraps every fileio operation in retry_fn which will retry 3 times with exp backoff, removes the keep idle connections time on pool since we're going to retry anyways.
closes #567
=> fix(aws): deal with closed connections via retries

crates/iceberg-catalog/src/service/authz/implementations/openfga/error.rs, crates/iceberg-catalog/src/service/authz/implementations/openfga/mod.rs, examples/access-control/docker-compose-build.yaml
also re-enables logs for the build docker-compose overlay in access-controls example
=> fix: ignore multiple writes of same permissions

crates/iceberg-catalog/src/service/authz/mod.rs
Add EnumString to `Catalog{Server,Project,Namespace,Table,User,Role,View}Action` so that the self-implemented Authorizer could translate from the string formatted action simpler. 
The original challenge was from the below method of Authorizer 
```rust
async fn is_allowed_view_action(
&self,
metadata: &RequestMetadata,
view_id: ViewIdentUuid,
action: impl From<&CatalogViewAction> + std::fmt::Display + Send,
) -> Result<bool> {
```
The `action` argument is a compose trait that is hard to be cast to `CatalogViewAction`, so when we were trying to translate it to our own AuthZ system's permission name, we have to do something like 
```rust
fn view_action_to_upm_perm(action: String) -> String {
match action.as_str() {
"can_drop" | "can_undrop" | "can_commit" | "can_rename" => …
```
=> chore: add EnumString to Catalog{resource}Action

examples/access-control/README.md, examples/trino-opa/README.md
Fixed typo. Changed `Ream` to `Realm` in examples.
=> doc: fix typo

Cargo.lock, Cargo.toml, crates/iceberg-catalog/migrations/20250328131139_fix_sequence_number.sql
Caution: this is a destructive change. Currently, it's possible through concurrent writes to get duplicate `table_id, sequence_number` tuples into `table_snapshot` by:
1. node A: load table
2. node B: load table
3. node A: add snapshot with sequence number incremented by one
4. node B: add snapshot with sequence number incremented by one
5. node A: commit
6. node B: commit
In general, this should not have happened often, since it's only possible when not sending a `RefSnapshotIdMatch` requirement:
```rust
#[serde(rename = "assert-ref-snapshot-id")]
RefSnapshotIdMatch {
/// The reference of the table to assert.
r#ref: String,
/// The snapshot id of the table to assert.
/// If the id is `None`, the ref must not already exist.
#[serde(rename = "snapshot-id")]
snapshot_id: Option<i64>,
},
```
=> fix!: drop duplicate sequence numbers in table snapshots & add index

docs/docs/developer-guide.md, site/docs/getting-started.md
* Refactored to `docker compose`
* fixed docker compose development setup to be `examples/minimal`
=> chore: refactor 'docker-compose' -> 'docker compose'

crates/iceberg-catalog/src/config.rs, crates/iceberg-catalog/src/implementations/postgres/migrations/mod.rs, crates/iceberg-catalog/src/lib.rs, crates/iceberg-catalog/src/request_metadata.rs, crates/iceberg-catalog/src/tracing.rs, docs/docs/configuration.md
BEGIN_COMMIT_OVERRIDE
fix: Use X-Forwarded-Host header for response in /config Endpoint
feat: Optionally disable the use of x-forwarded- headers
END_COMMIT_OVERRIDE
=> feat: Optionally disable the use of `x-forwarded-` headers

docs/docs/authentication.md
Adds doc snippets for terraform resources for Azure EntraID.
Two important caveats:
- Applications need to be marked with as `enterprise = true` (at least in my organization, it didn't work otherwise)
- Unlike the manual setup, the OpenID aud returned wasn't prefixed with `api://`. I also added a terraform output example that implicitly follows that.
=> add terraform doc snippets

crates/lakekeeper/src/service/authz/mod.rs, crates/lakekeeper/src/service/mod.rs
Adresses #1152
Slightly deviates from [this proposal](https://github.com/lakekeeper/lakekeeper/issues/1152#issuecomment-2939838153) because after adding `can_list_everything` to `warehouse` I suppose `HidingAuthorizer` would need not only a new field `allowed_namespace_actions` but also `allowed_warehouse_actions`.
I think this can be simplified by instead adding `blocked_actions` to `HidingAuthorizer`, which can then be used to block `warehouse:can_list_everything`, `namespace:can_list_everything`, and potentially actions on other objects later on. This also feels like a more natural extension of `HidingAuhorizer`.
With this in place the problem described in #1152 should be fixed by:
```Rust
authz.block_action(format!("warehouse:{}", CatalogWarehouseAction::CanListEverything)); …
```
=> test(HidingAuthorizer): enable blocking actions

.sqlx/query-1e8987175061207564b8f7dc762ba047ef581a31fefddc5172f794a25954f32b.json, crates/lakekeeper/src/implementations/postgres/tabular/table/common.rs
Previously rows where deleted from `table_statistics` instead of `partition_statistics`. My understanding of what happened:
- `remove_partition_statistics` gets only ever called after `remove_table_statistics` with [the same](https://github.com/lakekeeper/lakekeeper/blob/cfaad2861dce3998ad7514dc464c5320f7dadee6/crates/lakekeeper/src/catalog/tables.rs#L1527-L1547) snapshot ids.
- In that case the call of `remove_partition_statistics` should be a no-op and there are probably some orphan `partition_statistics` rows out there. To remove them, should we add a migration?
=> fix: `partition_statistics` deletion
